app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
new_training:
    path:      /new-training
    defaults:  { _controller: AppBundle:Training:new }
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
